name: rshuai
favicon: null
layout_spectrum: 0.00102
typography_spectrum: 0.06055
title: "Raymond Shuai's Scrapbook"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3d1bb'
    - '#54426c'
    - '#2d1d4c'
    - '#6e5d7d'
    - '#a0969e'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
