name: rshuai
favicon: null
layout_spectrum: 0.99657
typography_spectrum: 0.46326
title: Raymond Shuai
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
